# Generated by Django 3.1.7 on 2021-04-02 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='routine_time',
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_time1',
            field=models.TimeField(db_column='Starting Time', default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_time2',
            field=models.TimeField(db_column='Ending Time', default=datetime.time(0, 59)),
        ),
    ]
