# Generated by Django 3.1.7 on 2021-04-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0002_auto_20210402_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='routine_actno',
            field=models.IntegerField(db_column='Activity Number', default=0),
        ),
    ]
