# Generated by Django 3.1.7 on 2021-04-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0002_auto_20210402_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activityliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alist_username', models.CharField(db_column='User', max_length=20)),
                ('alist_activity', models.CharField(db_column='Activity', max_length=50)),
                ('alist_actno', models.IntegerField(db_column='Activity Number', default=0)),
                ('alist_time', models.IntegerField(db_column='Time Spent (Hours)', default=0)),
            ],
            options={
                'db_table': 'Activity List',
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_actno',
            field=models.IntegerField(db_column='Activity Number', default=0),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_time1',
            field=models.TimeField(db_column='Starting Time'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='routine_time2',
            field=models.TimeField(db_column='Ending Time'),
        ),
    ]
