# Generated by Django 3.1.7 on 2021-04-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0003_auto_20210410_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activityliste',
            new_name='Activitylist',
        ),
    ]
