# Generated by Django 3.1.7 on 2021-04-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routine', '0003_routine_routine_actno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='routine_actno',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_time1',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='routine_time2',
        ),
    ]
