# Generated by Django 3.1.7 on 2021-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_column='Username', max_length=20)),
                ('user_age', models.IntegerField(db_column='Age')),
                ('user_occupation', models.CharField(db_column='Occupation', max_length=50)),
            ],
            options={
                'db_table': 'User Info',
            },
        ),
    ]
